//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmwCarDataClient.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BmwCarDataClient.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        public static string Account_ClientId {
            get {
                return ResourceManager.GetString("Account_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia Codice.
        /// </summary>
        public static string Account_CopyCode {
            get {
                return ResourceManager.GetString("Account_CopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 1. GENERA CODICE DISPOSITIVO.
        /// </summary>
        public static string Account_GenerateCode {
            get {
                return ResourceManager.GetString("Account_GenerateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 2. APRI PORTALE BMW.
        /// </summary>
        public static string Account_OpenPortal {
            get {
                return ResourceManager.GetString("Account_OpenPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link di verifica BMW (Modificabile per Region USA/EU):.
        /// </summary>
        public static string Account_PortalUrlHeader {
            get {
                return ResourceManager.GetString("Account_PortalUrlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔐 3. RICHIEDI TOKEN DI ACCESSO.
        /// </summary>
        public static string Account_RequestToken {
            get {
                return ResourceManager.GetString("Account_RequestToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettagli Risposta Server (HTTP Status &amp; Payload):.
        /// </summary>
        public static string Account_ServerResponse {
            get {
                return ResourceManager.GetString("Account_ServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Inizializzazione Device Flow.
        /// </summary>
        public static string Account_Step1_Header {
            get {
                return ResourceManager.GetString("Account_Step1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Registrazione e Autorizzazione Portale BMW.
        /// </summary>
        public static string Account_Step2_Header {
            get {
                return ResourceManager.GetString("Account_Step2_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Riscatta Token di Accesso API.
        /// </summary>
        public static string Account_Step3_Header {
            get {
                return ResourceManager.GetString("Account_Step3_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Utente da copiare:.
        /// </summary>
        public static string Account_UserCodeLabel {
            get {
                return ResourceManager.GetString("Account_UserCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN (Telaio).
        /// </summary>
        public static string Account_Vin {
            get {
                return ResourceManager.GetString("Account_Vin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina Tutti i Contenitori.
        /// </summary>
        public static string Containers_DeleteAll {
            get {
                return ResourceManager.GetString("Containers_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea 10 container con raggruppamenti secondo default.
        /// </summary>
        public static string Containers_Deploy {
            get {
                return ResourceManager.GetString("Containers_Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ottieni Contenitori Attivi.
        /// </summary>
        public static string Containers_GetActive {
            get {
                return ResourceManager.GetString("Containers_GetActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ottieni Diagnosi Smart Maintenance.
        /// </summary>
        public static string Containers_GetSmartMaintenance {
            get {
                return ResourceManager.GetString("Containers_GetSmartMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Contenitori Attuali &amp; Pulizia (Risoluzione CU-124).
        /// </summary>
        public static string Containers_Section1_Header {
            get {
                return ResourceManager.GetString("Containers_Section1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Distribuzione Nuovi Contenitori (Sincronizzazione CSV).
        /// </summary>
        public static string Containers_Section2_Header {
            get {
                return ResourceManager.GetString("Containers_Section2_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribuisci i contenitori di abbonamento dati sull&apos;API BMW leggendo il file CSV..
        /// </summary>
        public static string Containers_Section2_Info {
            get {
                return ResourceManager.GetString("Containers_Section2_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Smart Maintenance (Diagnosi Pneumatici).
        /// </summary>
        public static string Containers_Section3_Header {
            get {
                return ResourceManager.GetString("Containers_Section3_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestione Contenitori BMW e Diagnostica.
        /// </summary>
        public static string Containers_Title {
            get {
                return ResourceManager.GetString("Containers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquista Token.
        /// </summary>
        public static string Dashboard_BuyToken {
            get {
                return ResourceManager.GetString("Dashboard_BuyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicca per acquistare il token illimitato online.
        /// </summary>
        public static string Dashboard_BuyTokenTooltip {
            get {
                return ResourceManager.GetString("Dashboard_BuyTokenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacchetto Clima &amp; Comfort.
        /// </summary>
        public static string Dashboard_ClimatePackage {
            get {
                return ResourceManager.GetString("Dashboard_ClimatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlla temperature, aria condizionata e sedili..
        /// </summary>
        public static string Dashboard_ClimatePackageDesc {
            get {
                return ResourceManager.GetString("Dashboard_ClimatePackageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacchetto Motore &amp; Autonomia.
        /// </summary>
        public static string Dashboard_DrivetrainPackage {
            get {
                return ResourceManager.GetString("Dashboard_DrivetrainPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato batteria, autonomia residua e chilometraggio..
        /// </summary>
        public static string Dashboard_DrivetrainPackageDesc {
            get {
                return ResourceManager.GetString("Dashboard_DrivetrainPackageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenza e Crediti.
        /// </summary>
        public static string Dashboard_LicenseHeader {
            get {
                return ResourceManager.GetString("Dashboard_LicenseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvio Flusso Dati Continuo (Live).
        /// </summary>
        public static string Dashboard_LiveStreamTitle {
            get {
                return ResourceManager.GetString("Dashboard_LiveStreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacchetto Manutenzione &amp; CBS.
        /// </summary>
        public static string Dashboard_MaintenancePackage {
            get {
                return ResourceManager.GetString("Dashboard_MaintenancePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scadenze olio, freni, liquido freni e check control..
        /// </summary>
        public static string Dashboard_MaintenancePackageDesc {
            get {
                return ResourceManager.GetString("Dashboard_MaintenancePackageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato MQTT.
        /// </summary>
        public static string Dashboard_MqttStatus {
            get {
                return ResourceManager.GetString("Dashboard_MqttStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interroga funzioni specifiche su richiesta tramite API REST. L&apos;attivazione scarica istantaneamente i dati del pacchetto e consuma i tuoi crediti..
        /// </summary>
        public static string Dashboard_PackagesInfo {
            get {
                return ResourceManager.GetString("Dashboard_PackagesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Tuoi Pacchetti Telematici (On-Demand).
        /// </summary>
        public static string Dashboard_PackagesTitle {
            get {
                return ResourceManager.GetString("Dashboard_PackagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Versione Premium Attiva - Richieste Illimitate.
        /// </summary>
        public static string Dashboard_PremiumActive {
            get {
                return ResourceManager.GetString("Dashboard_PremiumActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Premium (ricevuto via email).
        /// </summary>
        public static string Dashboard_PremiumTokenHeader {
            get {
                return ResourceManager.GetString("Dashboard_PremiumTokenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacchetto Sicurezza &amp; Porte.
        /// </summary>
        public static string Dashboard_SecurityPackage {
            get {
                return ResourceManager.GetString("Dashboard_SecurityPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitora lo stato di portiere, finestrini e allarmi..
        /// </summary>
        public static string Dashboard_SecurityPackageDesc {
            get {
                return ResourceManager.GetString("Dashboard_SecurityPackageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carica Stato Iniziale &amp; Avvia Streaming Live.
        /// </summary>
        public static string Dashboard_StartStreaming {
            get {
                return ResourceManager.GetString("Dashboard_StartStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ottiene lo stato iniziale e resta in ascolto costante tramite MQTT. Visualizza in tempo reale ogni evento dell&apos;auto (es. accensione, movimento, apertura porte)..
        /// </summary>
        public static string Dashboard_StreamingInfo {
            get {
                return ResourceManager.GetString("Dashboard_StreamingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Telemetria Live.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richieste di prova rimanenti:.
        /// </summary>
        public static string Dashboard_TrialRemaining {
            get {
                return ResourceManager.GetString("Dashboard_TrialRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tua BMW.
        /// </summary>
        public static string Dashboard_YourBmw {
            get {
                return ResourceManager.GetString("Dashboard_YourBmw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. BMW Account &amp; Auth.
        /// </summary>
        public static string Nav_Account {
            get {
                return ResourceManager.GetString("Nav_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Contenitori (Setup).
        /// </summary>
        public static string Nav_Containers {
            get {
                return ResourceManager.GetString("Nav_Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Dashboard Telemetria.
        /// </summary>
        public static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Anagrafica Veicolo.
        /// </summary>
        public static string Nav_VehicleInfo {
            get {
                return ResourceManager.GetString("Nav_VehicleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona la lingua di visualizzazione..
        /// </summary>
        public static string Settings_LanguageDesc {
            get {
                return ResourceManager.GetString("Settings_LanguageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua / Language.
        /// </summary>
        public static string Settings_LanguageHeader {
            get {
                return ResourceManager.GetString("Settings_LanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌙 Scuro (Dark).
        /// </summary>
        public static string Settings_ThemeDark {
            get {
                return ResourceManager.GetString("Settings_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli il tema visivo dell&apos;interfaccia..
        /// </summary>
        public static string Settings_ThemeDesc {
            get {
                return ResourceManager.GetString("Settings_ThemeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspetto (Tema).
        /// </summary>
        public static string Settings_ThemeHeader {
            get {
                return ResourceManager.GetString("Settings_ThemeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☀️ Chiaro (Light).
        /// </summary>
        public static string Settings_ThemeLight {
            get {
                return ResourceManager.GetString("Settings_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💻 Predefinito di Sistema.
        /// </summary>
        public static string Settings_ThemeSystem {
            get {
                return ResourceManager.GetString("Settings_ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni Applicazione.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spento.
        /// </summary>
        public static string Toggle_Off {
            get {
                return ResourceManager.GetString("Toggle_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attivo.
        /// </summary>
        public static string Toggle_On {
            get {
                return ResourceManager.GetString("Toggle_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica Dati Veicolo.
        /// </summary>
        public static string VehicleInfo_Download {
            get {
                return ResourceManager.GetString("VehicleInfo_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questa pagina interroga le informazioni anagrafiche e tecniche di base del tuo veicolo (es. colore, modello, anno) registrate sui server BMW..
        /// </summary>
        public static string VehicleInfo_Info {
            get {
                return ResourceManager.GetString("VehicleInfo_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dati Statici Veicolo (Basic Data).
        /// </summary>
        public static string VehicleInfo_Title {
            get {
                return ResourceManager.GetString("VehicleInfo_Title", resourceCulture);
            }
        }
    }
}
